Databases:
  AISHELL4: wav/{uri}.flac

Protocols:
  AISHELL4:
    SpeakerDiarization:
      only_words:
        train:
          uri: lists/train.txt
          annotation: rttm/{uri}.rttm
          annotated: uems/{uri}.uem
        development:
          uri: lists/dev.txt
          annotation: rttm/{uri}.rttm
          annotated: uems/{uri}.uem
        test:
          uri: lists/test.txt
          annotation: rttm/{uri}.rttm
          annotated: uems/{uri}.uem